#!/bin/bash
#~/.scripts/git-removeline
#Author: Khaja Minhajuddin <minhajuddin@cosmicvent.com>
#Delete matching line
#it takes one argument
#e.g. git removeline <matching pattern>

pattern=$1

for file in $(git grep "$pattern" | cut -d':'  -f 1 | uniq)
do
  echo "removing lines from $file"
  grep "$pattern" $file
  sed -i "/$pattern/d" $file
done
