#!/bin/bash

# if no args are passed we just do a git push
if [  $# -eq 0 ]
then
  b git push
  echo "git pushing in background"
  exit
fi

# if args are passed we commit and then do a push in the background
commit_message="$@"

git commit -m "$commit_message"
b git push
echo "git pushing in background"
